INSERT INTO CATALOG VALUES (1, CURRENT_TIMESTAMP, 'Men');
INSERT INTO CATALOG VALUES (2, CURRENT_TIMESTAMP, 'Women');
INSERT INTO CATALOG VALUES (3, CURRENT_TIMESTAMP, 'Kids');
INSERT INTO CATALOG VALUES (4, CURRENT_TIMESTAMP, 'Home');
INSERT INTO CATALOG VALUES (5, CURRENT_TIMESTAMP, 'DIY');

INSERT INTO PRODUCT VALUES (1, CURRENT_TIMESTAMP, 'Ball', 'Ball','sku1',1);
INSERT INTO PRODUCT VALUES (2, CURRENT_TIMESTAMP, 'T-shirt', 'T-shirt','sku2',1);
INSERT INTO PRODUCT VALUES (3, CURRENT_TIMESTAMP, 'Dress', 'Dress','sku3',2);
INSERT INTO PRODUCT VALUES (4, CURRENT_TIMESTAMP, 'Pants', 'Pants','sku4',2);
INSERT INTO PRODUCT VALUES (5, CURRENT_TIMESTAMP, 'Pokemon', 'Pokemon','sku5',3);
INSERT INTO PRODUCT VALUES (6, CURRENT_TIMESTAMP, 'Digimon', 'Digimon','sku6',3);
INSERT INTO PRODUCT VALUES (7, CURRENT_TIMESTAMP, 'Robot Kitchen', 'Robot Kitchen','sku7',4);
INSERT INTO PRODUCT VALUES (8, CURRENT_TIMESTAMP, 'Airfryer', 'Airfryer','sku8',4);
INSERT INTO PRODUCT VALUES (9, CURRENT_TIMESTAMP, 'Woods', 'ProductName1','sku9',5);
INSERT INTO PRODUCT VALUES (10, CURRENT_TIMESTAMP, 'Tenda', 'ProductName1','sku10',5);
